/* Screen words, English. Add pap / nl / es later as sibling objects. */
var WORDS = {
  app: "Pidi",
  help: "Help",
  noRun: "No run yet.",
  noRunMore: "Open the link they send you on WhatsApp.",
  hours: "10 PM to 2 AM",
  payWays: "Cash or bank transfer",
  twoDrops: "At most 2 drops a run",
  continueRun: "Continue",
  countCash: "Count the cash",
  addHome: "Add to Home Screen",
  sendRun: "Send a run",
  testRun: "TEST run. Not a real order.",
  tonight: "Tonight's run",
  startPickup: "Start pickup",
  pickUp: "Pick up",
  pickedUp: "Picked up",
  drop: "Drop",
  of: "of",
  delivered: "Delivered",
  bothDone: "Both drops done",
  oneDone: "Drop done",
  cashThisRun: "Cash collected this run",
  collect: "Collect",
  paysWith: "Pays with",
  giveChange: "Give",
  changeWord: "change",
  exact: "Exact amount. No change.",
  short: "Short",
  askRest: "Ask for the rest.",
  awaiting: "Awaiting transfer",
  paid: "Paid",
  noCash: "Don't collect cash",
  orderWord: "Order",
  includesFee: "Includes ƒ5 delivery",
  google: "Google Maps",
  waze: "Waze",
  call: "Call",
  whatsapp: "WhatsApp",
  bags: "bags",
  bag: "bag",
  endNight: "End of night",
  cashCollected: "Cash collected",
  youCounted: "You counted",
  compare: "Compare",
  matches: "It matches.",
  noCashYet: "No cash orders yet.",
  typeFlorins: "Type the florins you counted.",
  badNumber: "Use a number like 33.95.",
  smallDiff: "Small difference, noted.",
  checkDay: "Check within 24 hours.",
  checkNow: "Check now.",
  countedWord: "Counted",
  noSignal: "No signal. Saved on this phone.",
  damaged: "This link is damaged. Ask them to send it again.",
  oldLink: "This link is from an older app.",
  noDrops: "This link has no drop.",
  tooMany: "A run can have 2 drops at most.",
  opening: "Opening the run…",
  sendDriver: "Send to driver on WhatsApp",
  copyLink: "Copy the link",
  openHere: "Open this run on this phone",
  copied: "Copied.",
  secondDrop: "Add a second drop",
  another: "Another restaurant",
  makeError: "Fix the form, then send it."
};
